import Head from "next/head";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import { inter, poppins, roboto, cabin } from "./ui/fonts";
import { ThemeProvider } from "@/contexts/ThemeContext";
import styles from "./RootLayout.module.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeProvider>
      <div className={styles.layout}>
        <Head>
          <title>Try Angle Kids Science Curriculum</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <main className={`${cabin.className} ${styles.mainContent}`}>
          <div className={styles.container}>{children}</div>
        </main>
        <Footer />
      </div>
    </ThemeProvider>
  );
}
